language: node_js
node_js:
  - 10
branches:
  only:
    - published

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

script:
  - npm run generate

deploy:
  provider: pages
  local-dir: dist
  repo: popcorn-saint-brieuc/popcorn-saint-brieuc.github.io
  target-branch: master
  skip-cleanup: true
  github-token: ae59835d55bf584f54e5d2b1393951fd0273f1d6 # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: published
